export const BASE_URL = 'https://api.edamam.com/api/recipes/v2';

type FilterMetaData = {
	filter: string;
	title: string;
};
export const FILTER_PARAMETERS: Map<FilterMetaData, string[]> = new Map([
	[
		{
			filter: 'diet',
			title: 'Diet',
		},
		[
			'balanced',
			'high-fiber',
			'high-protein',
			'low-carb',
			'low-fat',
			'low-sodium',
		],
	],
	[
		{
			filter: 'health',
			title: 'Health',
		},
		[
			'alcohol-cocktail',
			'alcohol-free',
			'celery-free',
			'crustacean-free',
			'dairy-free',
			'DASH',
			'egg-free',
			'fish-free',
			'fodmap-free',
			'gluten-free',
			'immuno-supportive',
			'keto-friendly',
			'kidney-friendly',
			'kosher',
			'low-potassium',
			'low-sugar',
			'lupine-free',
			'Mediterranean',
			'mollusk-free',
			'mustard-free',
			'No-oil-added',
			'paleo',
			'peanut-free',
			'pecatarian',
			'pork-free',
			'red-meat-free',
			'sesame-free',
			'shellfish-free',
			'soy-free',
			'sugar-conscious',
			'sulfite-free',
			'tree-nut-free',
			'vegan',
			'vegetarian',
			'wheat-free',
		],
	],
	[
		{
			filter: 'cuisineType',
			title: 'Cuisine Type',
		},
		[
			'american',
			'asian',
			'british',
			'caribbean',
			'central europe',
			'chinese',
			'eastern europe',
			'french',
			'greek',
			'indian',
			'italian',
			'japanese',
			'korean',
			'mediterranean',
			'mexican',
			'middle eastern',
			'nordic',
			'south american',
			'south east asian',
			'world',
		],
	],
	[
		{
			filter: 'mealType',
			title: 'Meal Type',
		},
		['breakfast', 'brunch', 'lunch', 'snack', 'teatime', 'dinner'],
	],
	[
		{ filter: 'dishType', title: 'Dish Type' },
		[
			'alcohol cocktail',
			'biscuits and cookies',
			'bread',
			'cereals',
			'condiments and sauces',
			'desserts',
			'drinks',
			'egg',
			'ice cream and custard',
			'main course',
			'pancake',
			'pasta',
			'pastry',
			'pies and tarts',
			'pizza',
			'preps',
			'preserve',
			'salad',
			'sandwiches',
			'seafood',
			'side dish',
			'soup',
			'special occasions',
			'starter',
			'sweets',
		],
	],
]);
